[project]
name = "file-processing-pipeline"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "apscheduler>=3.11.3",
    "cryptography>=50.0.1",
    "fastapi>=0.141.1",
    "faststream[rabbit]>=0.7.7",
    "httpx>=0.28.1",
    "logfire[fastapi,sqlalchemy]>=5.1.1",
    "pandas>=3.0.6",
    "pymysql>=1.2.3",
    "pyright>=1.1.414",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "python-multipart>=0.0.32",
    "ruff>=0.16.9",
    "sqlmodel>=0.0.47",
    "tenacity>=9.1.4",
    "uvicorn>=0.54.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
